### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by gbradley** [asbjornh/react-tiny-crossfade#5]
Any chance the version constraints can be bumped to support v17?

**Comment by asbjornh** [comment]
Hey! Sorry for late reply.
Yeah that should be fine. I'm afraid I don't have much time for this these days though so I'm afraid I won't be able to promise an updated version in the short term

**Comment by gbradley** [comment]
No worries! We use it for a specific use-case in a bunch of projects, so they all point to a forked version for the time being.

**Comment by asbjornh** [comment]
I just published a new version. Should be available soon!
